markdown: kramdown
title: pages.iety.xyz
description: No comment.
include:
  - index.md
  - secret.md
  - ansible.md
  - markdown.md
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
